### ISSUE TITLE
functions from map or map2 statements not getting picked up

### ISSUE THREAD

**Issue by MattWiener** [ropenscilabs/packgraph#2]
Hi.  I'm very excited about packgraph - it's something I was actually looking for some months ago, but didn't come across your package until this morning.   However, I'm getting an error from igraph when running it:

Error in igraph::graph_from_data_frame(edges, vertices = nodes) : 
  Some vertex names in edge list are not listed in vertex data frame

And indeed, when I run the lines from the package until just before 
```
cl <- igraph::graph_from_data_frame(edges, directed = FALSE) %>% 
        igraph::clusters()
```
and then try 
`setdiff(nodes$name, c(edges$from, edges$to))`,
I do find some functions in nodes that are not in edges.  

The common denominator seems to be that the missing functions are being called in purrr::map or purrr::map2 statements.   So possibly the issue is that they don't have parentheses?   It's possible this is an issue with pkgapi::map_package rather than with your code.

Any thoughts welcome.

**Comment by mpadge** [comment]
Thanks for the excitement - this is a very preliminary package at the moment, but hoping for rapid development from here on. Could you please provide a minimal [`reprex`](https://reprex.tidyverse.org/) to demonstrate the problem. Seems like it should be easy to fix, but I first need to be able to reproduce it. Thanks!

**Comment by MattWiener** [comment]
OK.  Haven't exactly duplicated my error yet, but I have a minimal package at https://github.com/MattWiener/break.packgraph that seems to me to demonstrate a problem with functions called in map.    If you download that and run  pg_graph on it, it won't break (though it does get a warning), but the function my_toupper, which is called from main in a map statement, is out on its own.

Also, the arrows don't seem to reflect which function calls which other function, which makes the graph less useful than it could be.

I will keep trying to work out a minimal example for my error, but it's possible that taking care of functions that are only in map and map2 would also help clarify my error.

**Comment by mpadge** [comment]
> Also, the arrows don't seem to reflect which function calls which other function, which makes the graph less useful than it could be.

That's true, and will be rectified - feel free to open another issue to ping there for that to be implemented

**Comment by MattWiener** [comment]
OK.  Would you like me to leave this one open for the function in the map call being isolated, or close it and open a different issue?

**Comment by mpadge** [comment]
That commit fixed what seemed to be the main problem with your [`break.packgraph`](https://github.com/MattWiener/break.packgraph) example, but there are still a couple of further issues that that highlights, so I'll re-open to address those. Please note any further issues here as well, along with an additional issue for directional arrows. Thanks!

**Comment by mpadge** [comment]
No, actually, all seems to work now - please close if the issue is resolved

**Comment by MattWiener** [comment]
I'm still getting an isolated point.   Here's what I did from a clean session with nothing in the environment (I see I did load the new .004 version of packgraph).   I apologize if I'm missing something truly obvious.

> ls()
character(0)
> library(packgraph)
> temp <- packgraph::pg_graph(getwd())
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.2 (Maipo)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] packgraph_0.0.0.004

loaded via a namespace (and not attached):
 [1] igraph_1.2.5               Rcpp_1.0.3                 rstudioapi_0.11           
 [4] pkgapi_1.0.0               xml2_1.2.2                 magrittr_1.5              
 [7] roxygen2_7.0.2             tidyselect_1.1.0           R6_2.4.1                  
[10] rlang_0.4.7                fansi_0.4.1                stringr_1.4.0             
[13] dplyr_1.0.0                visNetwork_2.0.9           tools_3.6.2               
[16] packrat_0.5.0              cli_2.0.2                  withr_2.1.2               
[19] htmltools_0.5.0            ellipsis_0.3.1             assertthat_0.2.1          
[22] yaml_2.2.1                 digest_0.6.25              tibble_3.0.3              
[25] lifecycle_0.2.0            crayon_1.3.4               processx_3.4.1            
[28] break.packgraph_0.0.0.9000 purrr_0.3.4                callr_3.4.1               
[31] htmlwidgets_1.5.1          vctrs_0.3.2                ps_1.3.0                  
[34] glue_1.4.1                 stringi_1.4.6              compiler_3.6.2            
[37] pillar_1.4.6               generics_0.0.2             jsonlite_1.7.0            
[40] pkgconfig_2.0.3           
> 


Here's the image:
![image](https://user-images.githubusercontent.com/7340969/87778422-79277780-c82b-11ea-9c97-2681e8f87ebd.png)

Is it something in my dependencies?

**Comment by mpadge** [comment]
Ah, i see. And yes, your suspicions were right - it is the parsing of `purrr:map` by [`pkgapi`](https://github.com/r-lib/pkgapi):
``` r
library (pkgapi)
pkg_dir <- "/<path>/<to>/break.packgraph"
pkgapi::map_package (pkg_dir)
#> Warning: namespace 'break.packgraph' is not available and has been replaced
#> by .GlobalEnv when processing object '<unknown>'
#> $name
#> [1] "break.packgraph"
#> 
#> $exports
#> [1] "main"
#> 
#> $defs
#>             name     file line1 col1 line2 col2 exported
#> 1           main R/main.R     6    1    11    1     TRUE
#> 2     my_toupper R/main.R    19    1    21   26    FALSE
#> 3   non_function R/main.R    29    1    32    3    FALSE
#> 4 undoc_function R/main.R    34    1    34   39    FALSE
#> 
#> $calls
#>        file           from                              to type line1 line2
#> 1  R/main.R           main                      NA::tibble call     7     7
#> 2  R/main.R           main                      NA::mutate call     8     8
#> 3  R/main.R           main                         NA::map call     8     8
#> 4  R/main.R           main   break.packgraph::non_function call     9     9
#> 5  R/main.R           main break.packgraph::undoc_function call    10    10
#> 6  R/main.R     my_toupper                   base::toupper call    20    20
#> 7  R/main.R     my_toupper                     base::paste call    21    21
#> 8  R/main.R   non_function break.packgraph::undoc_function call    30    30
#> 9  R/main.R   non_function                    base::return call    31    31
#> 10 R/main.R   non_function                     base::paste call    31    31
#> 11 R/main.R undoc_function                     base::paste call    34    34
#>    col1 col2            str
#> 1    11   16         tibble
#> 2    21   26         mutate
#> 3    34   36            map
#> 4    12   23   non_function
#> 5    12   25 undoc_function
#> 6    11   17        toupper
#> 7    12   16          paste
#> 8    11   24 undoc_function
#> 9     3    8         return
#> 10   10   14          paste
#> 11   31   35          paste
```

<sup>Created on 2020-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

That only records `main` as calling `non_function` and `undoc_function`, but the `map` stuff gets lost within a call to `map`. So this issue should be pursued further via that repo. I'd be happy to open an issue, but you're the one who uncovered this, so I'd suggest it'd be better for you to open that, and include something like the `reprex` i pasted here. If you do, please ping me there as well, so i'll be kept informed. Nice work!

----

Edit: A fix could be complicated, because `pkgapi` works entirely by the [`getParseData()` function](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/getParseData.html), yet that function can only parse parameters passed to a `map` call as generic `SYMBOL`, and not as what they actually are, `SYBMOL_FUNCTION_CALL`:

``` r
pkg_dir <- "/<path>/<to>/break.packgraph"
f <- file.path (pkg_dir, "R", "main.R")
x <- getParseData (parse (f))
i <- which (x$text == "map")
j <- i - 1 + which (x$text [i:nrow (x)] == ")") [1]
x [i:j, ]
#>    line1 col1 line2 col2 id parent                token terminal       text
#> 66     8   34     8   36 66     68 SYMBOL_FUNCTION_CALL     TRUE        map
#> 68     8   34     8   36 68     81                 expr    FALSE           
#> 67     8   37     8   37 67     81                  '('     TRUE          (
#> 69     8   38     8   42 69     71               SYMBOL     TRUE      small
#> 71     8   38     8   42 71     81                 expr    FALSE           
#> 70     8   43     8   43 70     81                  ','     TRUE          ,
#> 75     8   45     8   54 75     77               SYMBOL     TRUE my_toupper
#> 77     8   45     8   54 77     81                 expr    FALSE           
#> 76     8   55     8   55 76     81                  ')'     TRUE          )
```

<sup>Created on 2020-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MattWiener** [comment]
moved to a pkgapi issue
